# Generated by Django 4.2.3 on 2023-08-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_customer_options_remove_customer_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.IntegerField(null=True),
        ),
    ]
