# Generated by Django 4.2.3 on 2023-08-05 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_foodimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="foodimage",
            old_name="product",
            new_name="food",
        ),
    ]
