# Generated by Django 4.2.3 on 2023-08-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_product_foodimage_food"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodimage",
            name="image",
            field=models.FileField(upload_to="core/images"),
        ),
    ]
