# Generated by Django 4.2.3 on 2023-08-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_foodimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="foods",
            name="max_buy",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="foods",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default="2", max_digits=6),
            preserve_default=False,
        ),
    ]
