# Generated by Django 4.2.3 on 2023-08-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_foods_max_buy_foods_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foods",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="foods",
            name="unit_price",
            field=models.IntegerField(),
        ),
    ]
