# Generated by Django 4.2.3 on 2023-08-21 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_otprequest_review_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="score",
        ),
    ]
