# Generated by Django 4.2.3 on 2023-08-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_order_address_order_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.IntegerField(),
        ),
    ]
